  # an async clone of the production mysql database
  mysql:
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    image: mariadb:10.4.34
    ports:
      - "3306:3306"
    volumes:
      - "/data/mysql:/var/lib/mysql"
      - "/mnt/replica-transfer-disk:/mnt/replica-transfer-disk"
    command: >
      mysqld
      --server-id=1
      --expire-logs-days=60
      --binlog-format=ROW
      --binlog-do-db=incfile_core
      --slow-query-log=ON
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=5
      --log-queries-not-using-indexes=OFF
      --innodb-buffer-pool-size=10G
      --innodb-buffer-pool-instances=8
      --log-slave-updates=ON
      --log-bin=mysqlbinlog
      --log-error=/var/log/mysql/maria.log
      --innodb-log-file-size=1G
      --innodb-log-files-in-group=2
      --innodb-flush-method=O_DIRECT
      --innodb-io-capacity=6000
      --innodb-io-capacity-max=12000
      --innodb-read-io-threads=8
      --innodb-write-io-threads=8
      --innodb-purge-threads=4
      --max-connections=1000
      --thread-cache-size=32
      --tmp-table-size=128M
      --max-heap-table-size=128M
      --query-cache-type=OFF
      --query-cache-size=0
      --relay-log=mysql-relay-bin
      --read-only=ON
      --gtid-domain-id=1
      --innodb-buffer-pool-dump-at-shutdown=OFF
      --max-binlog-size=10M
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

