services:
  ansible:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ansible
    hostname: ansible-devops
    restart: unless-stopped
    volumes:
      - ./:/etc/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - \\wsl.localhost\Ubuntu\home\ubuntu\.ssh:/root/.Hkeys:ro
    environment:
      - TAILSCALE_AUTH_KEY=your-auth-key-here
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ["sleep", "infinity"]
    logging: &logging
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "1"
